name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - next
      - 2.4.*

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup yarn
        run: npm install -g yarn

      - run: yarn
      - run: yarn ci
      - run: yarn docs:build
