name: Publish 2.4 Version

on:
  push:
    tags:
      - 2.4.*
    branches:
      - main
      - 2.4.*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup yarn
        run: npm install -g yarn

      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}